# Runs bandit security checker for code written in Python.
name: Bandit

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux:
    name: Bandit
    runs-on: ubuntu-latest
  
    steps:
      - name: Clone the git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install pip packages
        run: pip install -r third_party/requirements.txt

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libhwloc-dev

      # Scan is run only for the 'tools' folder.
      - name: Run Bandit
        run: |
          bandit -r tools
